# Generated by Django 5.1.7 on 2025-04-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_musician'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
