# Generated by Django 5.1.7 on 2025-04-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0003_musician_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='age',
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
